// src/lib/view3d.tsx
import { createEffect, onCleanup, onMount } from "solid-js";
import { StlRenderer } from "./test_scene";

const View3DComponent = () => {
 
  let stlRenderer = new StlRenderer();

  const animate = () => {
    requestAnimationFrame(animate);
    stlRenderer.render();
  };

          drawElement.appendChild(stlRenderer.renderer.domElement);
      stlRenderer.load3MF("/assets/3d/USB3.3MF");
      animate();
    
  

  return (
    <div style={{ max-width: "1000px" }} ref={drawElement}></div>
  );
};

export default View3DComponent;
l

// src/view3d.tsx

import {Component} from '@solenopsys/converged-renderer';
import {BasicSceneConfig} from "./scene";
import {load3MF} from "./loaders";

export const View3D:Component = (props:{modelUrl:string,textureUrl:string}) => {
  let config = new BasicSceneConfig();
  config.loadTexture(props.textureUrl);

  const animate = () => {
    requestAnimationFrame(animate);
    config.render();
  };

  //"/assets/3d/blouberg_sunrise_2_1k.hdr"

      //    drawElement.appendChild(stlRenderer.renderer.domElement);
      load3MF(props.modelUrl,config.scene);
   //   config.animate();
    
  return (  <div style={{maxWidth: "1000px"}}></div>);
};

export default View3D;
